import { createClient } from '@hey-api/openapi-ts';
import config from '../openapi-ts.config';

export async function generateApi(output?: string) {
  const resolved = await config;
  const destination = output ?? (resolved.output as string);
  await createClient({ ...resolved, output: destination });
  // Use the existing pinned formatter so the gauntlet cannot rewrite generated bytes.
  const formatter = Bun.spawn(
    [
      './node_modules/.bin/oxfmt',
      '--write',
      '--config',
      '.oxfmtrc.json',
      destination,
    ],
    { stdin: 'ignore', stdout: 'ignore', stderr: 'inherit' }
  );
  if ((await formatter.exited) !== 0)
    throw new Error('Generated API formatting failed.');
}

if (import.meta.main) await generateApi();
